#!/usr/bin/python3

import sys
import docker

print("Start of " + sys.argv[0])

expectedNumOfArgs=0
if len(sys.argv) != (expectedNumOfArgs + 1):
  #need to subtract one as 0 argument is the file name
  print("Wrong number of arguments expected " + str(expectedNumOfArgs) + " - got " + str(len(sys.argv)-1))
  print("Recieved args:")
  print(sys.argv)
  print("-")
  exit(1)

print("Checks docker is working by listing containers")

client = docker.DockerClient(base_url='unix://var/run/docker.sock')

print("Listing images:")
for image in client.images.list():
  print(image.id + "\t" + str(image.tags))

print("End of " + sys.argv[0])
exit(0)
