#!/usr/bin/python3

# Script which will delete a service and any associated routes
## Query to find all serivce routes
## Delete all service routes
## Delete Service

import sys
import requests
import json

print("Start of " + sys.argv[0])

expectedNumOfArgs=2
if len(sys.argv) != (expectedNumOfArgs + 1):
  #need to subtract one as 0 argument is the file name
  print("Wrong number of arguments expected " + str(expectedNumOfArgs) + " - got " + str(len(sys.argv)-1))
  print("Recieved args:")
  print(sys.argv)
  print("-")
  exit(1)

kongURL = sys.argv[1]
serviceName = sys.argv[2]

r = requests.get(kongURL + "/services/" + serviceName + "/routes")

if (r.status_code != 200):
  print(r.status_code)
  print(r.headers)
  print(r.content)
  print("ERROR bad return")
  exit(1)

jsonResp = json.loads(r.content.decode('utf-8'))

print("Service has " + str(len(jsonResp["data"])) + " routes")
for curRoute in jsonResp["data"]:
  print(" Deleting route for hosts " + str(curRoute["hosts"]) + " with ID " + curRoute["id"])
  r2 = requests.delete(kongURL + "/routes/" + curRoute["id"])
  if (r.status_code != 200):
    print(r.status_code)
    print(r.headers)
    print(r.content)
    print("ERROR bad return when deleting route")
    exit(1)

print(" Finished deleting routes - now deleteing service")
r2 = requests.delete(kongURL + "/services/" + serviceName)
if (r.status_code != 200):
  print(r.status_code)
  print(r.headers)
  print(r.content)
  print("ERROR bad return when deleting service")
  exit(1)

print("End of " + sys.argv[0])
exit(0)

