#!/usr/bin/python3

#./kong_delete_all_certs http://127.0.0.1:8001


#Test to add
'''
curl -i -X PUT --url http://127.0.0.1:8001/certificates/ -F cert=.fullchain.pem -F key=./privkey.pem -F snis=testcert.com1
curl -i -X PUT --url http://127.0.0.1:8001/certificates/ -F cert=.fullchain.pem -F key=./privkey.pem -F snis=testcert.co2m,t.ac.uk
curl -i -X PUT --url http://127.0.0.1:8001/certificates/ -F cert=.fullchain.pem -F key=./privkey.pem -F snis=testcert.co3m
curl -i -X PUT --url http://127.0.0.1:8001/certificates/ -F cert=.fullchain.pem -F key=./privkey.pem -F snis=testcert.co4m,sads.co.uk
curl -i -X PUT --url http://127.0.0.1:8001/certificates/ -F cert=.fullchain.pem -F key=./privkey.pem -F snis=testcert.co5m,t.ac.uk
curl -i -X PUT --url http://127.0.0.1:8001/certificates/ -F cert=.fullchain.pem -F key=./privkey.pem -F snis=testcert.co6m
'''


import sys
import requests
import json

print("Start of " + sys.argv[0])

expectedNumOfArgs=1
if len(sys.argv) != (expectedNumOfArgs + 1):
  #need to subtract one as 0 argument is the file name
  print("Wrong number of arguments expected " + str(expectedNumOfArgs) + " - got " + str(len(sys.argv)-1))
  print("Recieved args:")
  print(sys.argv)
  print("-")
  exit(1)

kongURL = sys.argv[1]
print(" deleting all certs for kong url " + kongURL)


r = requests.get(kongURL + "/certificates/")

if (r.status_code != 200):
  print(r.status_code)
  print(r.headers)
  print(r.content)
  print("ERROR bad return")
  exit(1)

jsonResp = json.loads(r.content.decode('utf-8'))

for cert in jsonResp["data"]:
  print("Deleting cert for " + str(cert["snis"]) + " (" + cert["id"] + ")")
  r = requests.delete(kongURL + "/certificates/" + cert["id"])
  if (r.status_code != 204):
    print(r.status_code)
    print(r.headers)
    print(r.content)
    print("ERROR bad return")
    exit(1)

print("End of " + sys.argv[0])
