#!/bin/sh

##Example:
#./kong_add_route_to_service \
#http://127.0.0.1:8001 \
#serv_name \
#http \
#route.host.com \
#/ppp \
#GET \
#null \
#null

##There is no checking to see if route already exists. Mutiple of the same route may exist if this is run mutiple times

KONG_URL=${1}
SERVICE_NAME=${2}
ROUTE_PROTOCOLS=${3}
ROUTE_HOSTS=${4}
ROUTE_PATHS=${5}
ROUTE_METHODS=${6}
ROUTE_STRIP_PATH=${7}
ROUTE_PRESERVE_HOST=${8}


NUMBER_EXPECTED_PARAMS=8

###This variable can be provided in development to get past curl cert errors
###export EXTRACURLOPTS="--insecure"
###EXTRACURLOPTS="--insecure"

echo "Installing new route for service ${2}"

if [ $# -ne ${NUMBER_EXPECTED_PARAMS} ]; then
  echo "Invalid paramaters expecting ${NUMBER_EXPECTED_PARAMS} but $# were supplied"
  exit 1
fi

if [ E${ROUTE_PRESERVE_HOST} != "Etrue" ]; then
  if [ E${ROUTE_PRESERVE_HOST} != "Efalse" ]; then
    if [ E${ROUTE_PRESERVE_HOST} = "Enull" ]; then
      ROUTE_PRESERVE_HOST=false
    else
      echo "Invalid ROUTE_PRESERVE_HOST param (${ROUTE_PRESERVE_HOST})"
      exit 1
    fi
  fi
fi
if [ E${ROUTE_STRIP_PATH} != "Etrue" ]; then
  if [ E${ROUTE_STRIP_PATH} != "Efalse" ]; then
    if [ E${ROUTE_STRIP_PATH} = "Enull" ]; then
      ROUTE_STRIP_PATH=true
    else
      echo "Invalid ROUTE_STRIP_PATH param (${ROUTE_STRIP_PATH})"
      exit 1
    fi
  fi
fi

SERVICE_JSON=$(curl ${EXTRACURLOPTS} -sS --fail -X GET --url ${KONG_URL}/services/${SERVICE_NAME} 2>&1)
RET=$?
SERVICE_EXISTS_IN_KONG=1
if [ ${RET} -ne 0 ]; then
  SERVICE_EXISTS_IN_KONG=0
  echo "ERROR Service not found in kong"
  echo "Output: ${SERVICE_JSON}"
  exit 1
fi

SERVICE_ID=$(echo ${SERVICE_JSON} | python -c "import sys, json; print json.load(sys.stdin)['id']")
ret=$?
if [ $ret -ne 0 ]; then
  echo "Could not find the service id"
  exit 1
fi
echo " - service id: ${SERVICE_ID}"

ROUTE_LIST_JSON=$(curl ${EXTRACURLOPTS} -sS --fail -X GET --url ${KONG_URL}/services/${SERVICE_NAME}/routes 2>&1)
RET=$?
if [ ${RET} -ne 0 ]; then
  echo "Query route failed - ${ret}"
  echo "Output: ${ROUTE_LIST_JSON}"
  exit 1
fi

NUMBER_OF_ROUTES=$(echo ${ROUTE_LIST_JSON} | python -c "import sys, json; print len(json.load(sys.stdin)['data'])")
echo " - Service has ${NUMBER_OF_ROUTES} routes"


##See https://docs.konghq.com/0.14.x/admin-api/#add-route
# protocols, hosts, paths and methods are all repeting criteris
CREATE_ROUTE_CMD="echo -sS --fail -X POST \
--url ${KONG_URL}/routes/ \
--data 'strip_path=${ROUTE_STRIP_PATH}' \
--data 'preserve_host=${ROUTE_PRESERVE_HOST}' \
--data 'service.id=${SERVICE_ID}' \
"

append_comma_seperated_value()
{
  VAR_NAME=${1}
  NEW_VAL=${2}
  if [ E${NEW_VAL} != "Enull" ]; then
    AA=$(echo ${NEW_VAL} | python -c "import sys; arr=sys.stdin.read().strip().split(','); arr2=list(map((lambda x: '--data \'${VAR_NAME}[]=' + x + '\''),arr)); print ' '.join(arr2)")
    CREATE_ROUTE_CMD="${CREATE_ROUTE_CMD} ${AA}"
  fi
}

append_comma_seperated_value protocols ${ROUTE_PROTOCOLS}
append_comma_seperated_value paths ${ROUTE_PATHS}
append_comma_seperated_value hosts ${ROUTE_HOSTS}
append_comma_seperated_value methods ${ROUTE_METHODS}

CMD=$(${CREATE_ROUTE_CMD})
CMD="curl ${EXTRACURLOPTS} ${CMD}"
eval ${CMD}
ret=$?
if [ $ret -ne 0 ]; then
  echo "ERROR Create route failed - ${ret}"
  exit 1
fi
echo "Route POST returned ${RET}"

echo "--------------------------"
echo "${0} completed sucessfully"
echo "--------------------------"

exit 0