#!/bin/sh

#Example:
#kong_install_service_and_route http://kong:8001 portainer http portainer 9000 "" https /portainer

KONG_URL=${1}
SERVICE_NAME=${2}
SERVICE_PROTOCOL=${3}
SERVICE_HOST=${4}
SERVICE_PORT=${5}
SERVICE_PATH=${6}
ROUTE_PROTOCOLS=${7}
ROUTE_HOSTS=${8}
ROUTE_PATHS=${9}
ROUTE_METHODS=${10}
ROUTE_STRIP_PATH=${11}
ROUTE_PRESERVE_HOST=${12}

NUMBER_EXPECTED_PARAMS=12

###This variable can be provided in development to get past curl cert errors
###export EXTRACURLOPTS="--insecure"
###EXTRACURLOPTS="--insecure"

echo "Installing service for ${2}"

if [ $# -ne ${NUMBER_EXPECTED_PARAMS} ]; then
  echo "Invalid paramaters expecting ${NUMBER_EXPECTED_PARAMS} but $# were supplied"
  exit 1
fi

if [ E${ROUTE_PRESERVE_HOST} != "Etrue" ]; then
  if [ E${ROUTE_PRESERVE_HOST} != "Efalse" ]; then
    if [ E${ROUTE_PRESERVE_HOST} = "Enull" ]; then
      ROUTE_PRESERVE_HOST=false
    else
      echo "Invalid ROUTE_PRESERVE_HOST param (${ROUTE_PRESERVE_HOST})"
      exit 1
    fi
  fi
fi
if [ E${ROUTE_STRIP_PATH} != "Etrue" ]; then
  if [ E${ROUTE_STRIP_PATH} != "Efalse" ]; then
    if [ E${ROUTE_STRIP_PATH} = "Enull" ]; then
      ROUTE_STRIP_PATH=true
    else
      echo "Invalid ROUTE_STRIP_PATH param (${ROUTE_STRIP_PATH})"
      exit 1
    fi
  fi
fi

if [ "E${ROUTE_PATHS}" = "E" ]; then
  echo "Invalid paramaters"
  exit 1
fi

SERVICE_JSON=$(curl ${EXTRACURLOPTS} -sS --fail -X GET --url ${KONG_URL}/services/${SERVICE_NAME} 2>&1)
RET=$?
SERVICE_EXISTS_IN_KONG=1
if [ ${RET} -ne 0 ]; then
  SERVICE_EXISTS_IN_KONG=0
  echo "Service not found in kong"
  echo "Output: ${SERVICE_JSON}"
  echo ""
  TMP=$(echo ${SERVICE_JSON} | grep 'Connection refused' )
  if [ "E${TMP}" != "E" ]; then
    echo "Detected connection refused"
    echo "Kong isn't running - terminating ${0}"
    echo ""
    exit 1
  fi
  TMP=$(echo ${SERVICE_JSON} | grep 'curl: (6) Could not resolve host:' )
  if [ "E${TMP}" != "E" ]; then
    echo "Detected Could not resolve host error"
    echo "Kong isn't running - terminating ${0}"
    echo ""
    exit 1
  fi
fi

if [ ${SERVICE_EXISTS_IN_KONG} -eq 0 ]; then
  SERVICE_JSON=$(curl ${EXTRACURLOPTS} -sS --fail -X POST \
                       --url ${KONG_URL}/services/ \
                       --data "name=${SERVICE_NAME}" \
                       --data "protocol=${SERVICE_PROTOCOL}" \
                       --data "host=${SERVICE_HOST}" \
                       --data "port=${SERVICE_PORT}" \
                       --data "path=${SERVICE_PATH}" \
                        2>&1)
  ret=$?
  if [ $ret -ne 0 ]; then
    echo "Create service failed - ${ret}"
    echo "Output: ${SERVICE_JSON}"
    echo ""
    exit 1
  fi
fi


#echo "OUTPUT WAS"
#echo "${CREATE_SERVICE_OUTPUT}"
#echo "END"
#
SERVICE_ID=$(echo ${SERVICE_JSON} | python -c "import sys, json; print json.load(sys.stdin)['id']")
ret=$?
if [ $ret -ne 0 ]; then
  echo "Could not find the service id"
  exit 1
fi
echo " - service id: ${SERVICE_ID}"

ROUTE_LIST_JSON=$(curl ${EXTRACURLOPTS} -sS --fail -X GET --url ${KONG_URL}/services/${SERVICE_NAME}/routes 2>&1)
RET=$?
if [ ${RET} -ne 0 ]; then
  echo "Query route failed - ${ret}"
  echo "Output: ${ROUTE_LIST_JSON}"
  exit 1
fi

NUMBER_OF_ROUTES=$(echo ${ROUTE_LIST_JSON} | python -c "import sys, json; print len(json.load(sys.stdin)['data'])")
echo " - Service has ${NUMBER_OF_ROUTES} routes"

if [ ${NUMBER_OF_ROUTES} -ne 0 ]; then
  echo "Terminating as service already has routes"
  echo "End of ${0}"
  exit 0
fi


##See https://docs.konghq.com/0.14.x/admin-api/#add-route
# protocols, hosts, paths and methods are all repeting criteris
CREATE_ROUTE_CMD="curl ${EXTRACURLOPTS} -sS --fail -X POST \
--url ${KONG_URL}/routes/ \
--data 'strip_path=${ROUTE_STRIP_PATH}' \
--data 'preserve_host=${ROUTE_PRESERVE_HOST}' \
--data 'service.id=${SERVICE_ID}' \
"

append_comma_seperated_value()
{
  VAR_NAME=${1}
  NEW_VAL=${2}
  if [ E${NEW_VAL} != "Enull" ]; then
    AA=$(echo ${NEW_VAL} | python -c "import sys; arr=sys.stdin.read().strip().split(','); arr2=list(map((lambda x: '--data \'${VAR_NAME}[]=' + x + '\''),arr)); print ' '.join(arr2)")
    CREATE_ROUTE_CMD="${CREATE_ROUTE_CMD} ${AA}"
  fi
}

append_comma_seperated_value protocols ${ROUTE_PROTOCOLS}
append_comma_seperated_value paths ${ROUTE_PATHS}
append_comma_seperated_value hosts ${ROUTE_HOSTS}
append_comma_seperated_value methods ${ROUTE_METHODS}

eval ${CREATE_ROUTE_CMD}
ret=$?
if [ $ret -ne 0 ]; then
  echo "Create route failed - ${ret}"
  echo "Cmd: ${CREATE_ROUTE_CMD}"
  exit 1
fi
echo "Route POST returned ${RET}"

echo "${0} completed sucessfully"

exit 0
