#!/bin/sh

echo "${0} start"

if [ ! -d ~/.ssh ]; then
  mkdir -p ~/.ssh
fi

# use SSH_KEY environment variable to create key file, if not exists
ssh_key_file="${HOME}/.ssh/id_rdocker"
if [ ! -f "$ssh_key_file" ]; then
  if [ ! -z "${SSH_KEY}" ]; then
    echo "SSH key passed through SSH_KEY environment variable: length check ${#SSH_KEY}"
    mkdir -p ~/.ssh
    if [ ! -z "${SPLIT_CHAR}" ]; then
      echo "${SSH_KEY}" | tr \'"${SPLIT_CHAR}"\' '\n' > "$ssh_key_file"
    else
      echo "${SSH_KEY}" > "$ssh_key_file"
    fi
    chmod 600 "$ssh_key_file"
  fi
else
  echo "Found $ssh_key_file file"
fi

echo "${0} end"

exit 0
