#!/bin/sh

echo "${0} start"
set -e

echo "You supplied ${#} params"

if [ ${#} -ne 3 ]; then
  echo "Error you should supply 2 params"
  echo "1: RDocker host"
  echo "2: Source directory"
  echo "3: Target directory on target host"
  echo "Note: if it dosen't exist the target dir will be created"
  echo "      if it does exist the target dir will be replaed"
  exit 1
fi

remote_host=${1}
SRC_DIR=${2}
TARG_DIR=${3}

echo "remote_host=${remote_host}"
echo "SRC_DIR=${SRC_DIR}"
echo "TARG_DIR=${TARG_DIR}"

if [ ! -d ${SRC_DIR} ]; then
  echo "Error - src dir dosen't exist"
  exit 1
fi

if [ ! -d ~/.ssh ]; then
  mkdir -p ~/.ssh
fi

# use SSH_KEY environment variable to create key file, if not exists
ssh_key_file="${HOME}/.ssh/id_rdocker"
if [ ! -f "$ssh_key_file" ]; then
  if [ ! -z "${SSH_KEY}" ]; then
    echo "SSH key passed through SSH_KEY environment variable: length check ${#SSH_KEY}"
    mkdir -p ~/.ssh
    if [ ! -z "${SPLIT_CHAR}" ]; then
      echo "${SSH_KEY}" | tr \'"${SPLIT_CHAR}"\' '\n' > "$ssh_key_file"
    else
      echo "${SSH_KEY}" > "$ssh_key_file"
    fi
    chmod 600 "$ssh_key_file"
  fi
else
  echo "Found $ssh_key_file file"
fi

echo "Running rsync"
rsync -Pavr  --delete -e "ssh -p ${SSH_PORT} -i ${ssh_key_file} -o StrictHostKeyChecking=no" --rsync-path="mkdir -p ${TARG_DIR} && rsync" ${SRC_DIR} ${remote_host}:${TARG_DIR}


echo "Complete"

echo "${0} completed successfully"
