#!/bin/sh

echo "${0} start"
set -e

echo "You supplied ${#} params"

if [ ${#} -ne 3 ]; then
  echo "Error you should supply 2 params"
  echo "1: RDocker host"
  echo "2: Source directory"
  echo "3: Target directory on target host"
  echo "Note: if it dosen't exist the target dir will be created"
  echo "      if it does exist the target dir will be replaed"
  exit 1
fi

remote_host=${1}
SRC_DIR=${2}
TARG_DIR=${3}

echo "remote_host=${remote_host}"
echo "SRC_DIR=${SRC_DIR}"
echo "TARG_DIR=${TARG_DIR}"

if [ ! -d ${SRC_DIR} ]; then
  echo "Error - src dir dosen't exist"
  exit 1
fi

rdockerinit

echo "Running rsync"
ssh_key_file="${HOME}/.ssh/id_rdocker"
rsync -Pavr  --delete -e "ssh -p ${SSH_PORT} -i ${ssh_key_file} -o StrictHostKeyChecking=no" --rsync-path="mkdir -p ${TARG_DIR} && rsync" ${SRC_DIR} ${remote_host}:${TARG_DIR}


echo "Complete"

echo "${0} completed successfully"
